const jsonHeaders = {
  "content-type": "application/json; charset=utf-8",
  "cache-control": "no-store"
};

const readinessLabels = {
  green: "Scale-ready",
  yellow: "Needs review",
  red: "High risk"
};

export function onRequestOptions() {
  return new Response(null, {
    status: 204,
    headers: {
      ...jsonHeaders,
      "access-control-allow-methods": "POST, OPTIONS",
      "access-control-allow-headers": "content-type"
    }
  });
}

export function onRequestGet() {
  return Response.json({
    ok: true,
    productId: "EV-PROD-001",
    version: "v0.18",
    endpoint: "POST /api/ai/analyze",
    mode: "deterministic mock",
    externalAi: false,
    message: "Send a selected scenario payload to receive a mocked analyst interpretation. No paid AI provider or secret is used."
  }, { headers: jsonHeaders });
}

export async function onRequestPost(context) {
  try {
    const payload = await readJson(context.request);
    const analysis = payload?.analysis || payload?.selectedScenario?.analysis || payload?.scenario?.analysis;
    const plan = payload?.plan || {};
    const scenario = payload?.selectedScenario || payload?.scenario || {};
    const action = payload?.action || "explain_plan";

    if (!analysis || typeof analysis !== "object") {
      return Response.json({
        ok: false,
        error: "Missing analysis payload.",
        expected: "Send plan, selectedScenario, activeMotions, and analysis from the simulator."
      }, { status: 400, headers: jsonHeaders });
    }

    const response = buildResponse({ plan, scenario, analysis, action, activeMotions: payload?.activeMotions || [] });
    return Response.json(response, { headers: jsonHeaders });
  } catch (error) {
    return Response.json({
      ok: false,
      error: "Invalid request body.",
      detail: error?.message || "Unable to parse JSON."
    }, { status: 400, headers: jsonHeaders });
  }
}

async function readJson(request) {
  const text = await request.text();
  if (!text.trim()) return {};
  return JSON.parse(text);
}

function buildResponse({ plan, scenario, analysis, action, activeMotions }) {
  const currency = plan.currency || "$";
  const company = plan.company || "This company";
  const scenarioName = scenario.name || "selected";
  const readiness = readinessLabels[analysis.readinessSignal] || "Needs review";
  const bestMotion = analysis.bestMotion?.name || activeMotions[0]?.name || "the strongest active motion";
  const weakestMotion = analysis.weakestMotion?.name || activeMotions[activeMotions.length - 1]?.name || "the weakest motion";
  const profit = money(analysis.profit, currency);
  const cac = money(analysis.cac, currency);
  const payback = Number.isFinite(Number(analysis.payback)) ? Number(analysis.payback).toFixed(1) : "n/a";
  const readinessScore = Number.isFinite(Number(analysis.readinessScore)) ? Number(analysis.readinessScore) : 0;

  const summaryByAction = {
    explain_plan: `${company} is evaluating the ${scenarioName} plan. The model shows ${readiness} readiness at ${readinessScore}/100, ${cac} blended CAC, ${payback} month payback, and ${profit} projected profit.`,
    diagnose_risk: `${company}'s main planning risk is concentration around ${weakestMotion}. Validate that motion before adding budget or headcount.`,
    improve_economics: `The fastest economics improvement path is to use ${bestMotion} as the benchmark, then reduce CAC or cost leakage in ${weakestMotion}.`,
    draft_decision_memo: `Decision memo prepared for ${company}'s ${scenarioName} scenario.`
  };

  const summary = summaryByAction[action] || summaryByAction.explain_plan;

  return {
    ok: true,
    productId: "EV-PROD-001",
    version: "v0.18",
    endpoint: "POST /api/ai/analyze",
    source: "cloudflare-pages-function",
    mode: "deterministic mock",
    externalAi: false,
    action,
    summary,
    diagnosis: [
      `Readiness signal: ${readiness} (${readinessScore}/100).`,
      `Best motion signal: ${bestMotion}.`,
      `Weakest motion signal: ${weakestMotion}.`,
      `Payback checkpoint: ${payback} months.`
    ],
    recommendations: [
      `Treat ${scenarioName} as the plan of record only after reviewing ${weakestMotion}.`,
      `Use ${bestMotion} as the reference motion for the next operating conversation.`,
      "Preserve this decision artifact before changing assumptions again."
    ],
    decisionMemo: [
      `Decision: Review the ${scenarioName} revenue motion plan for ${company}.`,
      `Strategic question: ${plan.question || "Not provided"}`,
      `Economic readout: ${profit} profit, ${cac} blended CAC, ${payback} month payback.`,
      `Analyst posture: proceed with the selected plan only after validating the weakest motion assumptions.`
    ].join("\n\n"),
    confidenceNotes: [
      "This response is generated by a deterministic backend mock.",
      "No external AI provider, paid API, secret, or authentication is active in v0.18.",
      "The endpoint exists to prove the future AI analyst path can live behind Cloudflare."
    ]
  };
}

function money(value, currency) {
  const numeric = Math.round(Number(value) || 0).toLocaleString();
  return `${currency}${numeric}`;
}
